### ISSUE TITLE
Adding support to .md posts

### ISSUE THREAD

**Issue by vitorestevam** [felippe-regazio/1post#6]
Markdown is simpler to write posts, but HTML offers more flexibility. I think that supporting both options should be a good option.

**Comment by vitorestevam** [comment]
Maybe I can support the development of this feature, but I think that we should do this without adding npm dependencies and I did not find a way to parse md to html without a lib

**Comment by felippe-regazio** [comment]
Thats the problem, this would add a dependency simply because write a markdown parser from scratch would be a bigger project than the 1post itself. But we can look at the tradeoffs: the problem with the dependency thing is that slows down the 1POST usage by NPX, but thats not a problem since it can be installed as a global package, and we can enforce it on the docs. By the other hand we could add it like a plugin. So we have two ways:

1. A plugin architecture: We create a 1post-markdown which you can install alongside 1post and it will allow you to parse markdown files for your posts. Instead of post.html we also allow a post.md file. This can be accomplished by first creating hooks for 1POST. The 1post-markdown plugin would simple add a new entry on blog config which when exists would enforce 1Post to find a 1post-markdown on the current global dependencies while parsing the posts

2. We just drop the purity philosophy and add a dependency

**Comment by danilowm** [comment]
I liked the plugin idea, can use it for other things in the future

**Comment by felippe-regazio** [comment]
Markdown is now supported since version `1.5.0`.
Usage: https://github.com/felippe-regazio/1post#markdown
